# Install and configure Supervisor
---

- assert:
    that:
      - supervisor_daemon_mode in supervisor_daemon_modes
      - supervisor_password is defined
      - supervisor_username is defined
      - supervisor_version is defined
  tags: [supervisor, always]

- block:
    - name: Remove Supervisor package
      package:
        name: supervisor
        state: absent

    - name: Install Supervisor Python packages
      pip:
        name: supervisor
        executable: pip2
        state: "{{ (supervisor_version == 'latest')|ternary('latest', omit) }}"
        version: "{{ (supervisor_version == 'latest')|ternary(omit, supervisor_version) }}"
      notify: restart supervisor
  become: yes
  tags: [supervisor, packages]

- block:
    - name: Create Supervisor directories
      file:
        name: '{{ item }}'
        mode: 0755
        state: directory
      loop:
        - /etc/supervisor/conf.d
        - /var/log/supervisor/

    - name: Create Supervisor socket group
      group:
        name: '{{ supervisor_socket_group }}'
        state: present
        system: yes

    - name: Configure Supervisor
      template:
        src: supervisord.conf.j2
        dest: /etc/supervisor/supervisord.conf
        mode: 0644
      notify: restart supervisor

    - name: Symlink Configuration for supervisorctl
      file:
        src: /etc/supervisor/supervisord.conf
        dest: /etc/supervisord.conf
        state: link

    - include_tasks: setup-service-{{ supervisor_daemon_mode }}.yml

    - meta: flush_handlers
  become: yes
  tags: [supervisor, config]

- name: Start Supervisor service
  service:
    name: supervisor
    enabled: yes
    state: started
  become: yes
  tags: [supervisor, services]
