s3fs_build_cfg: ''
s3fs_build_packages:
  - automake
  - autotools-dev
  - g++
  - git
  - libcurl4-gnutls-dev
  - libfuse-dev
  - libssl-dev
  - libxml2-dev
  - make
  - pkg-config
s3fs_repository_url: https://github.com/s3fs-fuse/s3fs-fuse.git
s3fs_version: v1.80
